GET http://localhost:3000/api/jobs/recruiter/1

###
POST http://localhost:3000/api/jobs/
Content-Type: application/json

{
     "recruiterId": "2",
      "jobsUniqueId": "3",
      "jobInfo": { 
      "image": "4dddddd654555",
      "jobTitle": "req.body.jobInfo.jobTitle",
      "jobType": "req.body.jobType",
      "jobDescription": "req.body.jobDescription",
      "requiredSkills": "req.body.requiredSkills",
      "jobRequirements": "req.body.jobRequirements",
      "jobLocation": "req.body.jobLocation"
    }
}