GET http://localhost:3000/api/jobs/

###
POST http://localhost:3000/api/jobs/
Content-Type: application/json

{
     "recruiterId": "1",
      "jobsUniqueId": "1",
      "jobs":{
      "jobInfo": { 
      "image": "4dddddd654555",
      "jobTitle": "req.body.jobInfo.jobTitle",
      "jobType": "req.body.jobType",
      "jobDescription": "req.body.jobDescription",
      "requiredSkills": "req.body.requiredSkills",
      "jobRequirements": "req.body.jobRequirements",
      "jobLocation": "req.body.jobLocation"
    }
  }
}